import {StyleSheet} from 'react-native';
import {COLORS, FONTS} from '../../Configs/constants';

export const styles = StyleSheet.create({
  containedButtonContainer: {
    width: '80%',
    height: 45,
    marginVertical: 6,
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 50,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  containedButtonText: {
    color: COLORS.WHITE,
    fontSize: FONTS.SIZE.MEDIUM,
    alignSelf: 'center',
    textTransform: 'uppercase',
    fontFamily: 'Montserrat-Bold',
  },
  outlinedButtonContainer: {
    width: '80%',
    height: 45,
    marginVertical: 6,
    backgroundColor: COLORS.WHITE,
    borderRadius: 50,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY,
  },
  outlinedButtonText: {
    color: COLORS.PRIMARY,
    fontSize: FONTS.SIZE.MEDIUM,
    alignSelf: 'center',
    textTransform: 'uppercase',
    fontFamily: 'Montserrat-Bold',
  },
  signInButtonContainer: {
    width: '94%',
    marginVertical: 10,
    backgroundColor: COLORS.WHITE,
    borderRadius: 50,
    paddingVertical: 15,
    paddingHorizontal: 12,
  },
  signInButtonText: {
    color: COLORS.PRIMARY,
    fontSize: FONTS.SIZE.REGULAR,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    textTransform: 'uppercase',
    fontFamily: 'Montserrat-Regular',
  },
  signInButtonTextDisabled: {
    color: COLORS.INACTIVE,
    fontSize: FONTS.SIZE.REGULAR,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    textTransform: 'uppercase',
    fontFamily: 'Montserrat-Regular',
  },
});
